In [54]:
import os
import pandas as pd
from pprint import pprint
from pathlib import Path
from dotenv import load_dotenv
from langchain_groq import ChatGroq
load_dotenv()
from src.eval_config import *
from IPython.display import display, Markdown

In [16]:
# Import all necessary libraries
from src.eval import (
                        get_score, 
                        save_file, 
                        get_results,
                        unanswerable_responses,
                        display_context_recall_failures
                    )

# Testset Generation

In [ ]:
REWRITE_PROMPT = """You are refining evaluation questions so each one is self-contained and unambiguous about its source.

You are given a QUESTION and the SOURCE it was generated from.

Rules:
1. If the question is already specific and clearly answerable on its own (it names the entity, gene, product, or topic it is about), return it UNCHANGED.
2. If the question uses vague references like "the company", "our", "the provided context", "this study" and does NOT name the specific source entity, rewrite it minimally to name the entity from the source. Change nothing else.
3. Do not add facts. Do not change the meaning. Only add the source identity when it is missing.

SOURCE: {source}
QUESTION: {question}

Return ONLY the final question text, nothing else."""

In [ ]:
def clean_source(filename):
    name = filename.split('.',1)[0]
    return name.replace('-',' ').replace("_"," ").strip()

def rewrite_question(llm, user_input, filename):
    source = clean_source(filename)
    prompt = REWRITE_PROMPT.format(source=source, question=user_input)
    return llm.invoke(prompt).content.strip()

In [ ]:
# llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0, groq_api_key=os.getenv("GROQ_API_KEY"))

In [ ]:
# df['user_input'] = df.apply(lambda row: rewrite_question(llm, row['user_input'], row['filename']), axis=1)

In [ ]:
# df.to_json("evaluation/testset/new_testset_rewritten.jsonl", orient='records', lines=True)

# Result Analysis

In [17]:
def result_df(k_value, file_path, df_dict={}):
    df_dict[k_value]=pd.read_json(file_path, orient="records", lines=True)
    return df_dict

In [18]:
file_path="evaluation/eval_results"
path = Path(file_path)
files = [str(file) for file in path.rglob("*") if file.is_file()]
sorted(files)

['evaluation/eval_results/rag_results_baseline.jsonl',
 'evaluation/eval_results/rag_results_v1.jsonl']

In [19]:
configs = ["k=4",
           "k=20, r=8 Hybrid=False, search=200",
           "k=10",
           "k=15", 
           "k=20",
           "k=20, r=5", 
           "k=20, r=8", 
           "k=20, r=8 udpated format", 
           "k=20, r=8, serach Hybrid", 
           "k=20, r=8 Hybrid=False"]

In [20]:
len(configs)

10

In [21]:
for k, df in zip(configs,sorted(files)):
    df_dict = result_df(k, df)

In [22]:
df_dict.keys()

dict_keys(['k=4', 'k=20, r=8 Hybrid=False, search=200'])

In [23]:
for k, df in df_dict.items():
    print("-"*50)
    print(k)
    print("-"*50)
    print(get_score(df))

--------------------------------------------------
k=4
--------------------------------------------------
llm_context_precision_with_reference    0.528249
context_recall                          0.837143
faithfulness                            0.623074
answer_relevancy                        0.812631
dtype: float64
--------------------------------------------------
k=20, r=8 Hybrid=False, search=200
--------------------------------------------------
llm_context_precision_with_reference    0.563356
context_recall                          0.788027
faithfulness                            0.597992
answer_relevancy                        0.825142
dtype: float64

In [24]:
sorted(files)

['evaluation/eval_results/rag_results_baseline.jsonl',
 'evaluation/eval_results/rag_results_v1.jsonl']

In [156]:
df = get_results("evaluation/eval_results/rag_results_baseline.jsonl")

In [216]:
get_score(df)

llm_context_precision_with_reference    0.528249
context_recall                          0.837143
faithfulness                            0.623074
answer_relevancy                        0.812631
dtype: float64

In [13]:
display_context_recall_failures(df, max_height=300)

Number of zero context recall cases: 2
Indices of unanswerable responses: [13, 41]

In [14]:
unanswerable_responses(df)

Number of unanswerable responses: 0

Empty DataFrame
Columns: [user_input, retrieved_contexts, response, reference, llm_context_precision_with_reference, context_recall, faithfulness, answer_relevancy]
Index: []

In [ ]:
len([0, 4, 5, 8, 14, 18, 20, 28, 30, 32, 35, 36, 37, 38, 41, 42, 43, 46, 47])
len([0, 4, 8, 14, 20, 28, 32, 35, 36, 41, 43, 47])

In [ ]:
[0, 4, 5, 8, 14, 18, 20, 28, 30, 32, 35, 36, 37, 38, 41, 42, 43, 46, 47]
index = 8

In [ ]:
df.iloc[index][['llm_context_precision_with_reference','context_recall', 'faithfulness','answer_relevancy']]

In [118]:
from pprint import pformat
import ast
print("-"*30, "User Input","-"*30)
print(pformat(df.iloc[index]['user_input']))
print('\n',"-"*30,"Response","-"*30)
print(pformat(df.iloc[index]['response']))
print('\n',"-"*30,"Reference","-"*30)
print(pformat(df.iloc[index]['reference']))
print('\n',"-"*30,"Retrieved Contexts","-"*30)
print(pformat(df.iloc[index]['retrieved_contexts']))

------------------------------ User Input ------------------------------

NameError: name 'index' is not defined

In [ ]:
word = "Annualized Estimated "
context_list = df.iloc[index]["retrieved_contexts"]

In [ ]:
[i for i, ctx in enumerate(context_list)if word in ctx]

In [ ]:
context_list[2]

In [123]:
i=15

In [124]:
print("-"*30, "User Input","-"*30)
display(Markdown(df['user_input'].iloc[i]))
print("-"*30, "Response","-"*30)
display(Markdown(df['response'].iloc[i]))
print("-"*30, "Reference Contexts","-"*30)
display(Markdown(df['reference'].iloc[i]))
print("-"*30, "Metrics","-"*30)
df[['llm_context_precision_with_reference', 'context_recall','faithfulness', 'answer_relevancy']].iloc[i]

------------------------------ User Input ------------------------------

What are BGCs and why they matther?

------------------------------ Response ------------------------------

**BGCs (Biosynthetic Gene Clusters)** are tightly packed groups of genes that together encode the enzymes required to produce a particular secondary‑metabolite (SM).
Typical BGCs contain genes for core biosynthetic enzymes such as polyketide synthases (PKSs) or non‑ribosomal peptide synthetases (NRPSs), as well as tailoring enzymes, transporters and regulatory elements. In a sequenced genome the presence of a BGC can be predicted because these conserved synthase/synthetase genes appear in a characteristic clustered arrangement.

**Why BGCs matter**

1. **Source of bioactive natural products** – The metabolites produced by BGCs include antibiotics, anticancer agents, immunosuppressants and other therapeutically valuable compounds.

2. **Hidden chemical diversity** – Many BGCs are silent or poorly expressed under standard laboratory conditions, so they represent a reservoir of undiscovered molecules that can be accessed by epigenetic modulation, co‑cultivation, precursor feeding, ribosomal engineering, or genome‑mining approaches.

3. **Guides drug discovery** – By identifying and activating BGCs researchers can deliberately generate novel SMs, expand structural diversity, and develop new drugs.

4. **Predictive power** – Bioinformatic tools can locate BGCs in any fully sequenced genome, allowing scientists to prioritize clusters for experimental activation and to infer the chemical structures they may produce.

Thus, BGCs are the genetic “blueprints” for secondary metabolites, and unlocking them is crucial for discovering and producing new biologically active compounds with high therapeutic utility.

------------------------------ Reference Contexts ------------------------------

BGCs are silent biosynthetic gene clusters in fungi that can be activated by small chemical elicitors, causing epigenetic alterations and enabling the production of bioactive secondary metabolites.

------------------------------ Metrics ------------------------------

llm_context_precision_with_reference    1.000000
context_recall                          1.000000
faithfulness                            0.823529
answer_relevancy                        0.680709
Name: 15, dtype: float64

In [126]:
questions = pd.read_json("evaluation/testset/new_testset.jsonl", orient='records', lines=True)

In [134]:
questions[['user_input']]

                                            user_input
0    i wanna know what Note 1 say about unearned re...
1    What the long term debt fair value be on June ...
2    I wanna know how the zero-trust end-to-end arc...
3    How zero‑day vulnerabilities affect us and wha...
4    How $2.1 billion cash outflow from operating a...
..                                                 ...
132  How does integrating photocatalysis with micro...
133  Can u tell me why we pick ERα for the docking ...
134  How does strictosidine's binding affinity comp...
135  Considering the QPlogHERG descriptor values th...
136  Which compound shows the strongest binding aff...

[137 rows x 1 columns]

In [141]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

display(questions[['user_input','filename']])

,user_input,filename
0,"i wanna know what Note 1 say about unearned revenue and how it fits with our debt proceeds usage for working capital, capex, stock repurchases, acquisitions and debt repayment, can you explain it in detail please",MSFT-anual-report.html
1,"What the long term debt fair value be on June 30, 2025 and how it compare to the 2024 number, can you tell me the amount and any difference in plain words?",MSFT-anual-report.html
2,"I wanna know how the zero-trust end-to-end architecture we got in our Security Development Lifecycle thing connect to the audit opinion on internal control over financial reporting, like did the audit mention anything about that architecture and what they say about it, can you explain it in detail?",MSFT-anual-report.html
3,How zero‑day vulnerabilities affect us and what sec filing requirements say about it?,MSFT-anual-report.html
4,How $2.1 billion cash outflow from operating assets and liabilities affect tax expense?,amd-20251227.html
5,"How do the potential adjustments by the Internl Revnue Servce affect our decision to reverse the valuation allowance and record a credit to income tax expense, given the four sources of jurisdictional taxable income—carryback of net operating losses, future reversals of taxable temporary differences, viable tax planning strategies, and future taxable income exclusive of reversals—and the uncertainties in multi‑jurisdictional tax rules?",amd-20251227.html
6,"Where can I locate the Performance-Based Restricted Stock Unit Agreement for Senior Vice Presidents and above under AMD’s 2004 Equity Incentive Plan, and the Executive Severance Plan for Senior Vice Presidents, including the specific exhibit numbers and the AMD Form 10‑K reports in which each document is incorporated by reference?",amd-20251227.html
7,How does the reported revenue growth relate to the revenue reductions caused by advertising reimbursements and product return rights?,amd-20251227.html
8,cloud-based infrastructure companies in e‑commerce sector,amzn-20251231.html
9,Based on the regulatory filing signed Feb 5 2026 can you explain how the company operational efficiencies in its fulfillment network are reflected in the cost of sales including any mention of shipping and payment processing costs and also what the filing signatures indicate about responsibility for these disclosures,amzn-20251231.html
10,"How does a stronger U.S. Dollar impact the company’s foreign‑exchange risk and the translation of assets, liabilities, and cash equivalents from its international stores?",amzn-20251231.html
11,What voting commitment did the Malone Group make concerning Liberty Broadband preferred stock?,chtr-20251231.html
12,How do state regulatroy agencies affect our busines?,chtr-20251231.html
13,How do local franchsie authorities affect asset impcat?,chtr-20251231.html
14,What information about investment accounting and tax provisions is included in the Consolidated Financial Statements according to the 10‑K filing?,goog-20251231.html
15,What are the key steps in Alhpabet Inc. adustments and how is imparemnt evaluated?,goog-20251231.html
16,"How do the internatonal tax policys, includng the 15% global minimum tax and the Jan 2026 OECD Side‑by‑Side Safe Harbor, potentially impact the companie's ability to fund its 2025 share repurchses totalling $240 million given its $126.8 billion cash position?",goog-20251231.html
17,How the company report fair value measurement of its marketable securities and link it to the valuation allowance for deferred tax assets as shown in its SEC Form 10‑K?,goog-20251231.html
18,What are the costs and regulatory consequences of privacy breaches and privacy‑related legislative changes for our ad business?,meta-20251231.html
19,Can you explan how the compnay's recent busines acquisitions releted to Intangible Assts were accounted for and what amounts were allocaed to them in the 2025 fiscal year?,meta-20251231.html
20,What is the ticker symobl META and how did the insider tradng claim resolve?,meta-20251231.html
21,"Considering the European Union‑U.S. data transfer restrictions that limit Meta’s ability to offer Facebook and Instagram in Europe, the recent announcements of significant products or features by Meta and its competitors, and the reported breaches of security or privacy, how might these combined factors affect Meta’s acquisition goodwill, intangible‑asset valuation, and integration considerations for senior management?",meta-20251231.html
22,How does the Comapny account for share-settled RSU expense over the vesting period?,mstr-20251231.html
23,What does the certifcate of designatons require for paying accrued dividends?,mstr-20251231.html
24,"How do the cost of capital considerations for preferred stock offerings interact with the requirement of having sufficient net profits and surplus to pay dividends, and what role do deferred taxes play in assessing the corporation’s ability to declare dividends?",mstr-20251231.html
25,"What is the company's approach to evaluating deferred tax assets, and how might its Bitcoin compliance obligations affect its ability to conduct spot market exchange transactions?",mstr-20251231.html
26,"As a risk analysist, can you explain the status of gross unrealized losses on Janurary 25, 2026 for the debt securities portfolio?",nvda-20260125.html
27,How does the infra support healthcere?,nvda-20260125.html
28,Who is NVIDIA's CFO and how does the company address the high energy consumption of GPUs used for generative AI?,nvda-20260125.html
29,What impact do AI regulation and licensing compliance have on revenue reduction for GPU products?,nvda-20260125.html
30,Alex can you tell me how the Company deals with concentration risks in its cash and cash equivalents and accounts receivable and what it does to limit credit risk from customers and the online marketplaces it uses especially since it seems like no single customer makes up more than ten percent of revenue or receivables,ptrn-20251231.html
31,"what lease cash pay on December 31, 2025?",ptrn-20251231.html
32,"How might severe ransomware attacks affect the company's financial amounts, such as the goodwill reported for 2023‑2025?",ptrn-20251231.html
33,"How does the companie ensure its liquidity while managin operatin cash flows for lease arrangements (6,119 in 2023, 7,410 in 2024, 9,102 in 2025) and at the same time mitigat­ing creditt risk related to its revolving credit facilitie with JPMorgan Chase (maturity Sep 2030, variable rate, covenant compliance) and the concentration risks from cash, cash equivalents and receivables held at high‑credit‑quality institutions and on third‑party online marketplaces?",ptrn-20251231.html
34,"As a Securities Compliance Analyst, how does the Compensation Committee’s review of the Compensation Discussion and Analysis satisfy the requirements of Regulation S‑K, specifically Item 402(b), and what disclosures are mandated by the SEC in this context?",tesla-anual-report-2026.htm
35,Wha is Item 11 re Mr. Musk's comp?,tesla-anual-report-2026.htm
36,"Considering that the final operational milestones are earned only after (i) the completion of the last performance milestone and (ii) the approval by disinterested board members of a CEO‑succession framework developed by Mr. Musk, how does the company’s evaluation of director independence—specifically the determination that there are no disqualifying factors under Nasdaq listing standards—support the fulfillment of these operational‑milestone conditions?",tesla-anual-report-2026.htm
37,What performance milestones are linked to the 2025 CEO Performance Award and how do they determine the vesting of the award?,tesla-anual-report-2026.htm
38,"Hey can u explain how the United States coal tax works for the first sale, who has to pay it, what counts as a producer and any exceptions that apply?",Excise Taxes.pdf
39,Hey i need to know where i can find the newest stuff about Pub. 510 like the IRS.gov\/Pub510 link and if they update it every year or only when big law changes cause i gotta check coal tax rules and maybe forms 720 can u tell me?,Excise Taxes.pdf
40,What penalty does a seller face for not posting the required notice at a retail pump when dyed diesel is used on inland waterways?,Excise Taxes.pdf
41,Which buyer account number and related certificate details must be provided to the position holder to qualify for the $0.001 per gallon nontaxable aviation kerosene tax rate?,Excise Taxes.pdf
42,"How $2,000 settlement affect my taxes?",Medical and Dental Expenses.pdf
43,How i use Worksheet A to figure my home improvement medical expense?,Medical and Dental Expenses.pdf
44,How can i use the IRS documnt upload tool for a car modifcation medcal expense?,Medical and Dental Expenses.pdf
45,IRS Form 1040 and 1040‑SR requirements for reporting excess medical‑expense reimbursements – what does the Taxpayer Advocate Service say about how to calculate and report the amount?,Medical and Dental Expenses.pdf
46,What documentation is needed to substantiate Keno expenses for tax purposes?,Miscellaneous Deductions.pdf
47,What does Pub. 463 say about deducting travel expenses for reservists?,Miscellaneous Deductions.pdf
48,"Why i cant deduct the whole $5,700 gambling loss even though i lost that much and how does that work with my other reservist expenses i got?",Miscellaneous Deductions.pdf
49,How can I make a payment using the IRS electronic options?,"Reporting Cash Payments of Over $10,000.pdf"
50,Social Security Number as the TIN for individuals?,"Reporting Cash Payments of Over $10,000.pdf"
51,"In a carr dealer scenario where a custumer pays $11,500 for a new car using $2,000 of U.S. currency and a cashier's checK for $9,500, how does the excemption for bank loan proceeds influence the requirement to file an IRS Form 8300, and what specific proof or documentation should be retained to demonstrate that the cashier's check is not treated as cash?","Reporting Cash Payments of Over $10,000.pdf"
52,How do i repot Form 8300 for a cash transction when i need personal ID and have a payment plan?,"Reporting Cash Payments of Over $10,000.pdf"
53,Taxpayer Advocate assistance for tax issues and how to contact them,Selling Your Home.pdf
54,"As a Residential Clean Energy Consultant, could you explain the eligibility period and specific credit provisions for qualified solar electric installations under the residential clean energy credit, including any relevant dates and how this credit interacts with other energy‑efficient home improvement credits?",Selling Your Home.pdf
55,Where can I get help at a local Taxpayer Assistance Center for reporting the sale of my home?,Selling Your Home.pdf
56,How do i subtract the tax credits for my solar energy system when i also need to put the QMID for the energy efficient home improvement credit after 2025?,Selling Your Home.pdf
57,"Where can I find IRS guidance on the basis of inherited property, specifically referencing Pub. 551?",Tax Information for Homeowners.pdf
58,What info does a Mortgage Interst Statment show for a small business owner?,Tax Information for Homeowners.pdf
59,How IRS tax assistance tools help with tenant‑stockholder income threshold?,Tax Information for Homeowners.pdf
60,How can I check my refund status and deduct mortgage points on my taxes?,Tax Information for Homeowners.pdf
61,What income is reported on Schedule K‑1 (Form 1041) for an expatriate retiree?,Tax Withholding and Estimated Tax.pdf
62,"How can a farmer or fisher receiving pension or annuity benefits that are delivered outside the United States avoid tax withholding by providing a home address in a U.S. territory, according to IRS guidance?",Tax Withholding and Estimated Tax.pdf
63,"Considering the instructions for Worksheet 2‑9 that guide you to determine your estimated tax liability by entering your period‑specific AGI (including any partnership, S‑corporation, or self‑employment income) and the guidance on who is required to pay estimated tax, how should an expatriate U.S. retiree calculate the amount of each estimated tax payment for the current year, what specific information must be entered on the worksheet, and under what circumstances can the retiree avoid making estimated tax payments altogether?",Tax Withholding and Estimated Tax.pdf
64,IRS tax assistance resources and steps to adjust tax withholding via Form W-4 for a part‑year expatriate retiree,Tax Withholding and Estimated Tax.pdf
65,How do I repoort Endowment Contract incme?,Taxable and Nontaxable Income.pdf
66,What is the tax treatmen of unemployment benefits and how does a beneficiary get taxed on estate or trust income?,Taxable and Nontaxable Income.pdf
67,"How does the $2,500 tax refund affect the $23,500 deferrl limit?",Taxable and Nontaxable Income.pdf
68,why 30% tax hold on partnership income?,U.S. Tax Guide for Aliens.pdf
69,"I need to know why a corporation's stock is automatically considered a United States real property holding corporation and also what the publicly traded exception says if we dont hold a big enough share, can you explain all that in detail?",U.S. Tax Guide for Aliens.pdf
70,Can I use Form 4868 to obtain an automatic filing extension when my work commute is defined by a 24‑hour travel window?,U.S. Tax Guide for Aliens.pdf
71,"How does the substantial presence test determine resident versus nonresident alien status for a taxpayer such as Robert Bach, including the effect of the first‑year choice, and what are the procedures, required forms, and processing timelines for filing an amended tax return if the residency classification is later corrected?",U.S. Tax Guide for Aliens.pdf
72,Can u tell me what the Catalog Number 64731W is and why it matters for my taxpayer rights?,Your Rights As A Taxpayer.pdf
73,If the IRS decides to examine my tax return can they still talk to other people like my neighbor or my bank even though I have a duly authorized representative and what can I do to get a list of who they talked to while the audit is going on because I want to know who knows my info and how the audit was started and what the rules are about third‑party contacts during examinations,Your Rights As A Taxpayer.pdf
74,Where are the collection appeal rights and taxpayer rights detailed in Publication 1660 and Publication 1?,Your Rights As A Taxpayer.pdf
75,What indemnification obligations does Zynga have toward WPT and its affiliates under the agreement?,AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.pdf
76,What terriory is defined and how does the licenced property survive after termination?,AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.pdf
77,"Can you explan the definintion of Royalty as set forth in the Agreement and describ how the 10% Royalty on cumulative Net Revenue from the WPT‑branded Zynga Poker Tournament Mode is calculatd, includin how it may be offest by any Annual Minimum Guarantee payments made during the Term?",AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.pdf
78,"I need to know what the Sponsor Business gotta do at the Stadium, like can they sell other stuff, do they have to work with the Concessionaire on logistics and storage, what happens if there is a product recall and who pays for any costs, and can the Club stop benefits if needed?",ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf
79,How does the sponsr's digtal and printed distributon in the Gameday Magzine relate to the ticket pricing for Playof Games and the LED carousel Signage benfits?,ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf
80,"What advertizing benefits does the Sponsor obtain each Contract Yeaar, and how are the extra Playoff Game payments calculated according to the agreement?",ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf
81,"As an Insurance Compliance Coordinator, could you explain what the uptime requirement for the ebix Web Siet is, how excess downtime is defined as a materiel breach, what the cure period of twenty‑four (24) hours entails, and under what conditions About may remove the ebix Links after notifying the President, CFO or CTO?",EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf
82,"According to the agreement, what are the required methods and timing for delivering notices, and how is the ""Money Channel Home Page"" defined in terms of its URL and its connection to the Insurance Center?",EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf
83,"In the co‑branding agreement dated January 19, 2001 between About.com and ebix.com, what are the specific indemnification responsibilities each party owes to the other, and what are the registered office addresses for About.com and ebix.com as listed in the agreement?",EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf
84,What GO-PAGE CORP say bout its reps and warranties?,GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf
85,"What are the specific conditions under which the licensor may terminate the license for a material breach related to the deletion or inaccessibility of a Content Item within the 24‑hour compliance window, and how does the confidentiality obligation in Section 10 apply during the term and for the five‑year post‑term period, including any noted exceptions such as required securities disclosures or indemnification obligations?",GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf
86,What happns to license fees if termintion occurs under Section 6.2(a) and how does Section 3.2 restrict the licencee's use?,GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf
87,iPass can u explain how fast we get a reply when we open a Severity One ticket and also what the wait is for a Severity Two case because i need to put the right times in my tickets and tell the hotline when to call back,IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
88,What the indemnifying party do?,IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
89,What confidentiality and data‑collection obligations must a Channel Partner meet before deploying the licensed software in a production environment?,IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
90,"What processes must a Channel Partner implement before deploying the Licensed Software, and how does the responsibility for first‑level technical support relate to these implementation requirements, especially concerning user profile and configuration management?",IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
91,How does SFDC's appointement of a sub‑reseller affect the reseller's compliancce obligations?,SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller Agreement.pdf
92,What does the Entire Agreement clause state in the Sub‑Reseller Agreement for the Reseller?,SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller Agreement.pdf
93,"What obligations does a Reseller have to ensure Sub-Reseller compliance under the Sub-Reseller Agreement, and how may the Sub-Reseller Agreement be executed in terms of counterparts?",SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller Agreement.pdf
94,How does the Control Panel influence the Advertising Cost Compensation settings?,SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate Agreement.pdf
95,Liability exclusion and affiliate eligibility for advertising cost compensation in the agreement,SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate Agreement.pdf
96,Whaat are the compenstation terms for Softwre Publisers product sales?,SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate Agreement.pdf

In [201]:
missing = set()
present = set()
idx = []

In [202]:
for i in range(len(questions)):
    usr_input = questions['user_input'].iloc[i]
    if usr_input in df['user_input'].values:
        present.add(questions['filename'].iloc[i])
        idx.extend(df.index[df["user_input"] == usr_input].tolist())
    else:
        missing.add(questions['filename'].iloc[i])

In [203]:
pprint(present & missing)
len(present & missing)

{'Anticancer potential of exosome-like nanoparticles isolated from Acorus '
 'calamus in breast cancer.pdf',
 'ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf',
 "Correlation of autophagy and Alzheimer's disease with special emphasis on "
 'the role of phosphodiesterase-4.pdf',
 'Excise Taxes.pdf',
 'Exploring microalgae-based strategies for the management of white spot '
 'syndrome virus- a comprehensive review.pdf',
 'Exploring the modern approaches to enhance fungal endophyte-derived '
 'bioactive secondary metabolites.pdf',
 'Exploring the therapeutic efficacy of Bai-Shao in mitigating comorbid '
 'epileptic seizures and cognitive impairment via inflammatory signaling '
 'pathways- insights from in silico and in vivo studies.pdf',
 'Fine-Tuning a Transformer Model for METTL3 Lead Optimization.pdf',
 'IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf',
 'MSFT-anual-report.html',
 'Medical and Dental Expenses.pdf',
 'Metabolic activity and pathway study of emerging contaminants biodegradation '
 'using a photo-bioelectrochemical system- a review.pdf',
 'Miscellaneous Deductions.pdf',
 'Potent phytoregulators from Pyrenacantha volubilis targeting ERα- a '
 'promising natural alternative for breast cancer therapy.pdf',
 'Reporting Cash Payments of Over $10,000.pdf',
 'SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller '
 'Agreement.pdf',
 'Selling Your Home.pdf',
 'SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate '
 'Agreement.pdf',
 'Tax Information for Homeowners.pdf',
 'Tax Withholding and Estimated Tax.pdf',
 'Taxable and Nontaxable Income.pdf',
 'TodosMedicalLtd_20190328_20-F_EX-4.10_11587157_EX-4.10_Marketing Agreement_ '
 'Reseller Agreement.pdf',
 'TubeMediaCorp_20060310_8-K_EX-10.1_513921_EX-10.1_Affiliate Agreement.pdf',
 'U.S. Tax Guide for Aliens.pdf',
 'Your Rights As A Taxpayer.pdf',
 'amd-20251227.html',
 'amzn-20251231.html',
 'chtr-20251231.html',
 'goog-20251231.html',
 'meta-20251231.html',
 'mstr-20251231.html',
 'nvda-20260125.html',
 'ptrn-20251231.html'}

33

In [189]:
pprint(present ^ missing)
len(present ^ missing)

{'AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content '
 'License Agreement.pdf',
 'EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf',
 'Exosome miR-152-3p derived from small intestinal epithelium modulates aging '
 'process in adipocytes.pdf',
 'Fabrication of Achyranthes aspera extract loaded ZIF-8 nanocomposite for '
 'lung cancer treatment, an in vitro assessment.pdf',
 'GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License '
 'Agreement.pdf',
 'tesla-anual-report-2026.htm'}

6

In [204]:
questions[['user_input', 'filename']]

,user_input,filename
0,"i wanna know what Note 1 say about unearned revenue and how it fits with our debt proceeds usage for working capital, capex, stock repurchases, acquisitions and debt repayment, can you explain it in detail please",MSFT-anual-report.html
1,"What the long term debt fair value be on June 30, 2025 and how it compare to the 2024 number, can you tell me the amount and any difference in plain words?",MSFT-anual-report.html
2,"I wanna know how the zero-trust end-to-end architecture we got in our Security Development Lifecycle thing connect to the audit opinion on internal control over financial reporting, like did the audit mention anything about that architecture and what they say about it, can you explain it in detail?",MSFT-anual-report.html
3,How zero‑day vulnerabilities affect us and what sec filing requirements say about it?,MSFT-anual-report.html
4,How $2.1 billion cash outflow from operating assets and liabilities affect tax expense?,amd-20251227.html
5,"How do the potential adjustments by the Internl Revnue Servce affect our decision to reverse the valuation allowance and record a credit to income tax expense, given the four sources of jurisdictional taxable income—carryback of net operating losses, future reversals of taxable temporary differences, viable tax planning strategies, and future taxable income exclusive of reversals—and the uncertainties in multi‑jurisdictional tax rules?",amd-20251227.html
6,"Where can I locate the Performance-Based Restricted Stock Unit Agreement for Senior Vice Presidents and above under AMD’s 2004 Equity Incentive Plan, and the Executive Severance Plan for Senior Vice Presidents, including the specific exhibit numbers and the AMD Form 10‑K reports in which each document is incorporated by reference?",amd-20251227.html
7,How does the reported revenue growth relate to the revenue reductions caused by advertising reimbursements and product return rights?,amd-20251227.html
8,cloud-based infrastructure companies in e‑commerce sector,amzn-20251231.html
9,Based on the regulatory filing signed Feb 5 2026 can you explain how the company operational efficiencies in its fulfillment network are reflected in the cost of sales including any mention of shipping and payment processing costs and also what the filing signatures indicate about responsibility for these disclosures,amzn-20251231.html
10,"How does a stronger U.S. Dollar impact the company’s foreign‑exchange risk and the translation of assets, liabilities, and cash equivalents from its international stores?",amzn-20251231.html
11,What voting commitment did the Malone Group make concerning Liberty Broadband preferred stock?,chtr-20251231.html
12,How do state regulatroy agencies affect our busines?,chtr-20251231.html
13,How do local franchsie authorities affect asset impcat?,chtr-20251231.html
14,What information about investment accounting and tax provisions is included in the Consolidated Financial Statements according to the 10‑K filing?,goog-20251231.html
15,What are the key steps in Alhpabet Inc. adustments and how is imparemnt evaluated?,goog-20251231.html
16,"How do the internatonal tax policys, includng the 15% global minimum tax and the Jan 2026 OECD Side‑by‑Side Safe Harbor, potentially impact the companie's ability to fund its 2025 share repurchses totalling $240 million given its $126.8 billion cash position?",goog-20251231.html
17,How the company report fair value measurement of its marketable securities and link it to the valuation allowance for deferred tax assets as shown in its SEC Form 10‑K?,goog-20251231.html
18,What are the costs and regulatory consequences of privacy breaches and privacy‑related legislative changes for our ad business?,meta-20251231.html
19,Can you explan how the compnay's recent busines acquisitions releted to Intangible Assts were accounted for and what amounts were allocaed to them in the 2025 fiscal year?,meta-20251231.html
20,What is the ticker symobl META and how did the insider tradng claim resolve?,meta-20251231.html
21,"Considering the European Union‑U.S. data transfer restrictions that limit Meta’s ability to offer Facebook and Instagram in Europe, the recent announcements of significant products or features by Meta and its competitors, and the reported breaches of security or privacy, how might these combined factors affect Meta’s acquisition goodwill, intangible‑asset valuation, and integration considerations for senior management?",meta-20251231.html
22,How does the Comapny account for share-settled RSU expense over the vesting period?,mstr-20251231.html
23,What does the certifcate of designatons require for paying accrued dividends?,mstr-20251231.html
24,"How do the cost of capital considerations for preferred stock offerings interact with the requirement of having sufficient net profits and surplus to pay dividends, and what role do deferred taxes play in assessing the corporation’s ability to declare dividends?",mstr-20251231.html
25,"What is the company's approach to evaluating deferred tax assets, and how might its Bitcoin compliance obligations affect its ability to conduct spot market exchange transactions?",mstr-20251231.html
26,"As a risk analysist, can you explain the status of gross unrealized losses on Janurary 25, 2026 for the debt securities portfolio?",nvda-20260125.html
27,How does the infra support healthcere?,nvda-20260125.html
28,Who is NVIDIA's CFO and how does the company address the high energy consumption of GPUs used for generative AI?,nvda-20260125.html
29,What impact do AI regulation and licensing compliance have on revenue reduction for GPU products?,nvda-20260125.html
30,Alex can you tell me how the Company deals with concentration risks in its cash and cash equivalents and accounts receivable and what it does to limit credit risk from customers and the online marketplaces it uses especially since it seems like no single customer makes up more than ten percent of revenue or receivables,ptrn-20251231.html
31,"what lease cash pay on December 31, 2025?",ptrn-20251231.html
32,"How might severe ransomware attacks affect the company's financial amounts, such as the goodwill reported for 2023‑2025?",ptrn-20251231.html
33,"How does the companie ensure its liquidity while managin operatin cash flows for lease arrangements (6,119 in 2023, 7,410 in 2024, 9,102 in 2025) and at the same time mitigat­ing creditt risk related to its revolving credit facilitie with JPMorgan Chase (maturity Sep 2030, variable rate, covenant compliance) and the concentration risks from cash, cash equivalents and receivables held at high‑credit‑quality institutions and on third‑party online marketplaces?",ptrn-20251231.html
34,"As a Securities Compliance Analyst, how does the Compensation Committee’s review of the Compensation Discussion and Analysis satisfy the requirements of Regulation S‑K, specifically Item 402(b), and what disclosures are mandated by the SEC in this context?",tesla-anual-report-2026.htm
35,Wha is Item 11 re Mr. Musk's comp?,tesla-anual-report-2026.htm
36,"Considering that the final operational milestones are earned only after (i) the completion of the last performance milestone and (ii) the approval by disinterested board members of a CEO‑succession framework developed by Mr. Musk, how does the company’s evaluation of director independence—specifically the determination that there are no disqualifying factors under Nasdaq listing standards—support the fulfillment of these operational‑milestone conditions?",tesla-anual-report-2026.htm
37,What performance milestones are linked to the 2025 CEO Performance Award and how do they determine the vesting of the award?,tesla-anual-report-2026.htm
38,"Hey can u explain how the United States coal tax works for the first sale, who has to pay it, what counts as a producer and any exceptions that apply?",Excise Taxes.pdf
39,Hey i need to know where i can find the newest stuff about Pub. 510 like the IRS.gov\/Pub510 link and if they update it every year or only when big law changes cause i gotta check coal tax rules and maybe forms 720 can u tell me?,Excise Taxes.pdf
40,What penalty does a seller face for not posting the required notice at a retail pump when dyed diesel is used on inland waterways?,Excise Taxes.pdf
41,Which buyer account number and related certificate details must be provided to the position holder to qualify for the $0.001 per gallon nontaxable aviation kerosene tax rate?,Excise Taxes.pdf
42,"How $2,000 settlement affect my taxes?",Medical and Dental Expenses.pdf
43,How i use Worksheet A to figure my home improvement medical expense?,Medical and Dental Expenses.pdf
44,How can i use the IRS documnt upload tool for a car modifcation medcal expense?,Medical and Dental Expenses.pdf
45,IRS Form 1040 and 1040‑SR requirements for reporting excess medical‑expense reimbursements – what does the Taxpayer Advocate Service say about how to calculate and report the amount?,Medical and Dental Expenses.pdf
46,What documentation is needed to substantiate Keno expenses for tax purposes?,Miscellaneous Deductions.pdf
47,What does Pub. 463 say about deducting travel expenses for reservists?,Miscellaneous Deductions.pdf
48,"Why i cant deduct the whole $5,700 gambling loss even though i lost that much and how does that work with my other reservist expenses i got?",Miscellaneous Deductions.pdf
49,How can I make a payment using the IRS electronic options?,"Reporting Cash Payments of Over $10,000.pdf"
50,Social Security Number as the TIN for individuals?,"Reporting Cash Payments of Over $10,000.pdf"
51,"In a carr dealer scenario where a custumer pays $11,500 for a new car using $2,000 of U.S. currency and a cashier's checK for $9,500, how does the excemption for bank loan proceeds influence the requirement to file an IRS Form 8300, and what specific proof or documentation should be retained to demonstrate that the cashier's check is not treated as cash?","Reporting Cash Payments of Over $10,000.pdf"
52,How do i repot Form 8300 for a cash transction when i need personal ID and have a payment plan?,"Reporting Cash Payments of Over $10,000.pdf"
53,Taxpayer Advocate assistance for tax issues and how to contact them,Selling Your Home.pdf
54,"As a Residential Clean Energy Consultant, could you explain the eligibility period and specific credit provisions for qualified solar electric installations under the residential clean energy credit, including any relevant dates and how this credit interacts with other energy‑efficient home improvement credits?",Selling Your Home.pdf
55,Where can I get help at a local Taxpayer Assistance Center for reporting the sale of my home?,Selling Your Home.pdf
56,How do i subtract the tax credits for my solar energy system when i also need to put the QMID for the energy efficient home improvement credit after 2025?,Selling Your Home.pdf
57,"Where can I find IRS guidance on the basis of inherited property, specifically referencing Pub. 551?",Tax Information for Homeowners.pdf
58,What info does a Mortgage Interst Statment show for a small business owner?,Tax Information for Homeowners.pdf
59,How IRS tax assistance tools help with tenant‑stockholder income threshold?,Tax Information for Homeowners.pdf
60,How can I check my refund status and deduct mortgage points on my taxes?,Tax Information for Homeowners.pdf
61,What income is reported on Schedule K‑1 (Form 1041) for an expatriate retiree?,Tax Withholding and Estimated Tax.pdf
62,"How can a farmer or fisher receiving pension or annuity benefits that are delivered outside the United States avoid tax withholding by providing a home address in a U.S. territory, according to IRS guidance?",Tax Withholding and Estimated Tax.pdf
63,"Considering the instructions for Worksheet 2‑9 that guide you to determine your estimated tax liability by entering your period‑specific AGI (including any partnership, S‑corporation, or self‑employment income) and the guidance on who is required to pay estimated tax, how should an expatriate U.S. retiree calculate the amount of each estimated tax payment for the current year, what specific information must be entered on the worksheet, and under what circumstances can the retiree avoid making estimated tax payments altogether?",Tax Withholding and Estimated Tax.pdf
64,IRS tax assistance resources and steps to adjust tax withholding via Form W-4 for a part‑year expatriate retiree,Tax Withholding and Estimated Tax.pdf
65,How do I repoort Endowment Contract incme?,Taxable and Nontaxable Income.pdf
66,What is the tax treatmen of unemployment benefits and how does a beneficiary get taxed on estate or trust income?,Taxable and Nontaxable Income.pdf
67,"How does the $2,500 tax refund affect the $23,500 deferrl limit?",Taxable and Nontaxable Income.pdf
68,why 30% tax hold on partnership income?,U.S. Tax Guide for Aliens.pdf
69,"I need to know why a corporation's stock is automatically considered a United States real property holding corporation and also what the publicly traded exception says if we dont hold a big enough share, can you explain all that in detail?",U.S. Tax Guide for Aliens.pdf
70,Can I use Form 4868 to obtain an automatic filing extension when my work commute is defined by a 24‑hour travel window?,U.S. Tax Guide for Aliens.pdf
71,"How does the substantial presence test determine resident versus nonresident alien status for a taxpayer such as Robert Bach, including the effect of the first‑year choice, and what are the procedures, required forms, and processing timelines for filing an amended tax return if the residency classification is later corrected?",U.S. Tax Guide for Aliens.pdf
72,Can u tell me what the Catalog Number 64731W is and why it matters for my taxpayer rights?,Your Rights As A Taxpayer.pdf
73,If the IRS decides to examine my tax return can they still talk to other people like my neighbor or my bank even though I have a duly authorized representative and what can I do to get a list of who they talked to while the audit is going on because I want to know who knows my info and how the audit was started and what the rules are about third‑party contacts during examinations,Your Rights As A Taxpayer.pdf
74,Where are the collection appeal rights and taxpayer rights detailed in Publication 1660 and Publication 1?,Your Rights As A Taxpayer.pdf
75,What indemnification obligations does Zynga have toward WPT and its affiliates under the agreement?,AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.pdf
76,What terriory is defined and how does the licenced property survive after termination?,AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.pdf
77,"Can you explan the definintion of Royalty as set forth in the Agreement and describ how the 10% Royalty on cumulative Net Revenue from the WPT‑branded Zynga Poker Tournament Mode is calculatd, includin how it may be offest by any Annual Minimum Guarantee payments made during the Term?",AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.pdf
78,"I need to know what the Sponsor Business gotta do at the Stadium, like can they sell other stuff, do they have to work with the Concessionaire on logistics and storage, what happens if there is a product recall and who pays for any costs, and can the Club stop benefits if needed?",ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf
79,How does the sponsr's digtal and printed distributon in the Gameday Magzine relate to the ticket pricing for Playof Games and the LED carousel Signage benfits?,ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf
80,"What advertizing benefits does the Sponsor obtain each Contract Yeaar, and how are the extra Playoff Game payments calculated according to the agreement?",ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf
81,"As an Insurance Compliance Coordinator, could you explain what the uptime requirement for the ebix Web Siet is, how excess downtime is defined as a materiel breach, what the cure period of twenty‑four (24) hours entails, and under what conditions About may remove the ebix Links after notifying the President, CFO or CTO?",EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf
82,"According to the agreement, what are the required methods and timing for delivering notices, and how is the ""Money Channel Home Page"" defined in terms of its URL and its connection to the Insurance Center?",EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf
83,"In the co‑branding agreement dated January 19, 2001 between About.com and ebix.com, what are the specific indemnification responsibilities each party owes to the other, and what are the registered office addresses for About.com and ebix.com as listed in the agreement?",EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.pdf
84,What GO-PAGE CORP say bout its reps and warranties?,GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf
85,"What are the specific conditions under which the licensor may terminate the license for a material breach related to the deletion or inaccessibility of a Content Item within the 24‑hour compliance window, and how does the confidentiality obligation in Section 10 apply during the term and for the five‑year post‑term period, including any noted exceptions such as required securities disclosures or indemnification obligations?",GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf
86,What happns to license fees if termintion occurs under Section 6.2(a) and how does Section 3.2 restrict the licencee's use?,GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf
87,iPass can u explain how fast we get a reply when we open a Severity One ticket and also what the wait is for a Severity Two case because i need to put the right times in my tickets and tell the hotline when to call back,IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
88,What the indemnifying party do?,IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
89,What confidentiality and data‑collection obligations must a Channel Partner meet before deploying the licensed software in a production environment?,IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
90,"What processes must a Channel Partner implement before deploying the Licensed Software, and how does the responsibility for first‑level technical support relate to these implementation requirements, especially concerning user profile and configuration management?",IpassInc_20181203_8-K_EX-99.1_11445874_EX-99.1_Reseller Agreement.pdf
91,How does SFDC's appointement of a sub‑reseller affect the reseller's compliancce obligations?,SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller Agreement.pdf
92,What does the Entire Agreement clause state in the Sub‑Reseller Agreement for the Reseller?,SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller Agreement.pdf
93,"What obligations does a Reseller have to ensure Sub-Reseller compliance under the Sub-Reseller Agreement, and how may the Sub-Reseller Agreement be executed in terms of counterparts?",SalesforcecomInc_20171122_10-Q_EX-10.1_10961535_EX-10.1_Reseller Agreement.pdf
94,How does the Control Panel influence the Advertising Cost Compensation settings?,SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate Agreement.pdf
95,Liability exclusion and affiliate eligibility for advertising cost compensation in the agreement,SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate Agreement.pdf
96,Whaat are the compenstation terms for Softwre Publisers product sales?,SouthernStarEnergyInc_20051202_SB-2A_EX-9_801890_EX-9_Affiliate Agreement.pdf